language:       ocaml
before_install: sudo apt-get update -qq
install:        sudo apt-get install -y ocaml ocaml-nox ocaml-native-compilers camlp4-extra time libgtk2.0 libgtksourceview2.0
script:
  - time make BUILD_COQIDE=yes build-coq
  - time make TIMECMD=time all
  - time make install
after_script:
  - test -f UniMath/Ktheory/Circle.vo
  - test -f sub/coq/user-contrib/UniMath/Ktheory/Circle.vo
